### ISSUE TITLE
XML DOM error while parsing HTML string

### ISSUE THREAD

**Issue by Ayush-Rawal** [g6ling/react-native-html-parser#10]
I'm getting the error "[xmldom fatalError] end tag name: p is not match the current start tagName:undefined" while trying to parse an html string

```javascript
import DOMParser from 'react-native-html-parser';
const parser = new DOMParser.DOMParser();

render(){
const parsed = parser.parseFromString(item.excerpt, 'text/html');
return <Text style={styles.ListItem_brief}>{parsed}...</Text>
}
```
the string being parsed is:

"<p>Disney Theatrical Productions and Frozen have partnered with The Actors Fund to celebrate International Women’s Day with two special events: “Women’s Day on Broadway: &hellip;<br /><a href=\"https://thewaltdisneycompany.com/disneys-frozen-partners-actors-fund-celebrate-international-womens-day/\" class=\"button button-more\">Read More</a><\/p>\\n"

![img_20180129_201518 1](https://user-images.githubusercontent.com/31813648/35516330-7f1c8e42-0531-11e8-8dad-8defccf0f347.jpg)

I apologise for the bad pic, the phone doesn't allow screenshots

**Comment by lhtin** [comment]
I had the problome too. I think is that the parseFromString doesn't completely impelement [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) standard. the parseFromString is more strict then the standard one. So, I think you can try [xmldom](https://github.com/jindw/xmldom)

**Comment by Andrfas** [comment]
Added PR that should fix this issue
https://github.com/g6ling/react-native-html-parser/pull/11
