### ISSUE TITLE
[xmldom error] element parse error

### ISSUE THREAD

**Issue by GeldgeilerGnom** [g6ling/react-native-html-parser#17]
`.then((res) => {
                const parser = new DOMParser.DOMParser();
                const parsed = parser.parseFromString(res, 'text/html');
                alert(parsed);`

the error pops up and then the alert with the right parsed html code comes. but I cant work with it because of this error, please help me.

`"dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "lodash": "^4.17.11",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-html-parser": "^0.0.5",
    "react-native-i18n": "^2.0.15",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^10.0.0",
    "react-native-progress": "^3.6.0",
    "react-native-restart": "^0.0.10",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-vector-icons": "^6.4.2",
    "react-native-webview": "^7.4.2",
    "react-navigation": "^3.9.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  }`

![image](https://user-images.githubusercontent.com/32291654/68688596-5859a480-056f-11ea-8605-9a7bce4f856d.png)

**Comment by g6ling** [comment]
If you are ok, could you show html code?
