### ISSUE TITLE
Problems parsing HTML String with named html entities

### ISSUE THREAD

**Issue by amelzer** [g6ling/react-native-html-parser#4]
As the title says, I am having problems with named HTML entities.

Steps to reproduce:

```
import DOMParser from 'react-native-html-parser';

const html = `<p>Hello world <b>world</b> <i>foo</i> bar hahh&ouml;</p>`;    
const parser = new DOMParser.DOMParser();
const parsed = parser.parseFromString(html, 'text/html');
```

Expected behaviour:
HTML string gets parsed

Actual behaviour:

![domerror kopie](https://cloud.githubusercontent.com/assets/1628866/19983901/331d326e-a20c-11e6-9222-a87d9f18fe6e.jpeg)

**Comment by g6ling** [comment]
This library don't support `&ouml;` character set. If you want use more character set, you can edit [entity-map.js](https://github.com/g6ling/react-native-html-parser/blob/master/entity-map.js). 
In this case, edit like
```js
...
    'quot': '"',
	'apos': "'",
	'ouml': 'ö', // add this line
....
```
And If you cannot find `entity-map.js` file, change react-native-html-parser version to 0.0.4 in package.json.

**Comment by thucld** [comment]
i'm having a same problem:
[xmldom error] entity not found:&reg;

view-source:https://thethaovanhoa.vn/mu-498ct149/trang-1.htm

![device-2018-02-08-101635](https://user-images.githubusercontent.com/29792418/35953858-3b5192ea-0cb9-11e8-9ecb-8a2a10a02652.png)

**Comment by Andrfas** [comment]
Created PR https://github.com/g6ling/react-native-html-parser/pull/11 with upgraded file

**Comment by Gibbz** [comment]
Im getting this error with &deg; Which is the degree symbol.
Found here: http://www.bom.gov.au/vic/observations/vicall.shtml
